"""criando tabela de veiculos

Revision ID: 26393baa98d8
Revises: f6f248c753eb
Create Date: 2025-09-03 21:32:10.203359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26393baa98d8'
down_revision: Union[str, Sequence[str], None] = 'f6f248c753eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.Enum('CAR', 'TRUCK', name='vehicletype'), nullable=False),
    sa.Column('fuel_type', sa.Enum('GASOLINE', 'DIESEL', 'ETHANOL', 'ELECTRIC', 'HYBRID', name='fueltype'), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'INACTIVE', name='vehiclestatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('license_expiration', sa.DateTime(), nullable=True),
    sa.Column('inspection_expiration', sa.DateTime(), nullable=True),
    sa.Column('insurance_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate'),
    schema='natudrive'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles', schema='natudrive')
    # ### end Alembic commands ###
