"""adicionando campo phone_number users model

Revision ID: 54ee2e1d7a12
Revises: 68ed68154262
Create Date: 2025-08-26 20:33:42.270033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ee2e1d7a12'
down_revision: Union[str, Sequence[str], None] = '68ed68154262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True), schema='natudrive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number', schema='natudrive')
    # ### end Alembic commands ###
