"""criando tabela de drivers

Revision ID: 8751b1fd4764
Revises: 54ee2e1d7a12
Create Date: 2025-09-03 21:16:27.590755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8751b1fd4764'
down_revision: Union[str, Sequence[str], None] = '54ee2e1d7a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_license', sa.String(), nullable=False),
    sa.Column('license_category', sa.String(), nullable=True),
    sa.Column('license_expiration', sa.DateTime(), nullable=False),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['natudrive.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['natudrive.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='natudrive'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers', schema='natudrive')
    # ### end Alembic commands ###
