"""adicionando campos de auditoria tabela de veiculos

Revision ID: cdfb473dd197
Revises: 26393baa98d8
Create Date: 2025-09-03 21:38:15.662564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdfb473dd197'
down_revision: Union[str, Sequence[str], None] = '26393baa98d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='natudrive')
    op.add_column('vehicles', sa.Column('updated_by', sa.UUID(), nullable=True), schema='natudrive')
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(), nullable=False), schema='natudrive')
    op.add_column('vehicles', sa.Column('created_by', sa.UUID(), nullable=False), schema='natudrive')
    op.create_foreign_key(None, 'vehicles', 'users', ['updated_by'], ['id'], source_schema='natudrive', referent_schema='natudrive')
    op.create_foreign_key(None, 'vehicles', 'users', ['created_by'], ['id'], source_schema='natudrive', referent_schema='natudrive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', schema='natudrive', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', schema='natudrive', type_='foreignkey')
    op.drop_column('vehicles', 'created_by', schema='natudrive')
    op.drop_column('vehicles', 'created_at', schema='natudrive')
    op.drop_column('vehicles', 'updated_by', schema='natudrive')
    op.drop_column('vehicles', 'updated_at', schema='natudrive')
    # ### end Alembic commands ###
